### ISSUE TITLE
null 响应

### ISSUE THREAD

**Issue by serialt** [bapaws/answer#13]
play上下载的，输入什么都只收到null，检查过，token是配置好了的

**Comment by bapaws** [comment]
Google Play 上的版本存在权限的问题，已经提交新的了，可以先试试：https://github.com/bapaws/answer/releases/download/v1.1.0/app-release.apk

**Comment by minchaozhang** [comment]
不好意思，之前 Google Play 版本的 API Key 的保存功能存在 Bug，今天刚刚更新了

感谢您的反馈

**Comment by bapaws** [comment]
不好意思，之前 Google Play 上的版本存在 API Key 保存失败的 Bug，今天刚刚更新了新版本

感谢反馈

**Comment by bapaws** [comment]
可下载最新的 1.1.1 版本：[app-release.apk](https://github.com/bapaws/answer/releases/download/v1.1.1/app-release.apk)
